---
driver:
  name: dokken
  chef_version: 14.12.3 # Unable to use a newer Chef version due to outdated cookbooks
  privileged: true

provisioner:
  name: dokken
  data_bags_path: "./test/fixtures/data_bags"

transport:
  name: dokken

platforms:
- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN apt-get -y install rsyslog

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN apt-get -y install rsyslog

- name: ubuntu-20.04
  driver:
    image: dokken/ubuntu-20.04
    pid_one_command: /lib/systemd/systemd
    intermediate_instructions:
      - RUN apt-get -y install rsyslog

verifier:
  name: inspec

.common_attributes: &common_attributes
  gitlab-patroni:
    secrets:
      backend: chef_vault
      path: secrets
      key: gitlab-patroni
    patroni:
      bind_interface: <%= ENV['VAGRANT_INTERFACE_NAME'] %>  # autodetect if nil
      config:
        bootstrap:
          pg_hba:
            - host postgres gitlab-superuser 192.168.0.0/11 md5
            - host all gitlab-superuser 192.168.0.0/11 md5
            - host all gitlab-superuser 127.0.0.1/32 md5
            - host all pgwatch2 127.0.0.1/32 md5
            - host replication gitlab-replicator 127.0.0.1/32 md5
            - host replication gitlab-replicator 192.168.0.0/11 md5
    postgresql:
      parameters:
        shared_buffers: 512MB
        shared_preload_libraries: pg_stat_statements,pg_wait_sampling,pg_stat_kcache
      monitoring:
        pgwatch2:
          enable: true
  consul:
    config:
      bootstrap_expect: 3
      datacenter: local
      ui: true
      enable_syslog: true
      log_level: INFO
  gitlab_consul:
    cluster_nodes:
      - 192.168.33.2
      - 192.168.33.3
      - 192.168.33.4
    cluster:
      bind_interface: <%= ENV['VAGRANT_INTERFACE_NAME'] %>  # autodetect if nil
      tls:
        ssl_key:
          secret_source: chef_vault
          secret_bag: secrets
          item: gitlab-consul-cluster
        ssl_cert:
          secret_source: chef_vault
          secret_bag: secrets
          item: gitlab-consul-cluster
        ssl_chain:
          secret_source: chef_vault
          secret_bag: secrets
          item: gitlab-consul-cluster
  prometheus:
    labels:
      env: test

suites:
  - name: patroni
    run_list:
      - recipe[gitlab-patroni::kitchen_chef_sslerror_fix]
      - recipe[gitlab_consul::cluster]
      - recipe[gitlab-patroni::default]
      - recipe[gitlab-patroni::consul]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      <<: *common_attributes

  - name: postgresql_extension_pg_wait_sampling
    run_list:
      - recipe[gitlab-patroni::kitchen_chef_sslerror_fix]
      - recipe[gitlab-patroni::default]
    attributes:
      <<: *common_attributes
    verifier:
      inspec_tests:
        - test/integration/postgresql/extensions/pg_wait_sampling

  - name: postgresql_extension_pg_stat_kcache
    run_list:
      - recipe[gitlab-patroni::kitchen_chef_sslerror_fix]
      - recipe[gitlab-patroni::default]
    attributes:
      <<: *common_attributes
    verifier:
      inspec_tests:
        - test/integration/postgresql/extensions/pg_stat_kcache

  - name: postgresql_pgwatch2
    run_list:
      - recipe[gitlab-patroni::kitchen_chef_sslerror_fix]
      - recipe[gitlab_consul::cluster]
      - recipe[gitlab-patroni::default]
      - recipe[gitlab-patroni::consul]
      - recipe[gitlab-patroni::kitchen_enable_patroni]
      - recipe[gitlab-patroni::pgwatch2]
      - recipe[gitlab-patroni::pgwatch2_postgresql_user]
    attributes:
      <<: *common_attributes
    verifier:
      inspec_tests:
        - test/integration/postgresql/monitoring/pgwatch2
