---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: "./test/fixtures/data_bags"

platforms:
  - name: ubuntu-16.04

suites:
  - name: patroni-1
    driver:
      network:
        - ["private_network", {ip: "192.168.33.2"}]
    run_list:
      - recipe[gitlab-patroni::default]
  - name: patroni-2
    driver:
      network:
        - ["private_network", {ip: "192.168.33.3"}]
    run_list:
      - recipe[gitlab-patroni::default]
  - name: patroni-3
    driver:
      network:
        - ["private_network", {ip: "192.168.33.4"}]
    run_list:
      - recipe[gitlab-patroni::default]
