---
driver:
  name: digitalocean
  private_networking: false
  ipv6: false
  region: <%= ENV['GITLAB_DO_REGION'] || "nyc3" %>

provisioner:
  name: chef_zero
  data_bags_path: "test/data_bags"

platforms:
  - name: ubuntu-16-04-x64
    driver_config:
      server_name: <%= ENV['USER'] || 'iamgroot' %>-kitchen-test-1604.template.gitlab-cookbooks.ci.gitlab.test

verifier:
  name: inspec

transport:
  name: rsync
  ssh_key: <%= ENV['GITLAB_DO_SSH_KEY'] || "~/.ssh/id_rsa" %>
  username: root

suites:
  - name: default
    run_list:
      - recipe[template::default]
    attributes: {}
