Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false
